name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      # Cache pnpm store
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm exec nx run-many -t lint --parallel=1
      - run: pnpm exec nx run-many -t test --parallel=1
      - run: pnpm exec nx run-many -t build --parallel=1
      - run: pnpm exec nx run-many -t typecheck --parallel=1
